// src/components/objects/ParticleCloud.jsx
import { Sparkles } from "@react-three/drei";

export default function ParticleCloud({
  position = [0, 0, 0],
  color = "#00cfff",
  count = 60,
}) {
  return (
    <Sparkles
      position={position}
      count={count}
      scale={3}
      size={1.5}
      speed={0.4}
      color={color}
    />
  );
}

// src/components/objects/ParticleCloud.vue
<script setup>
import { Sparkles } from '@tresjs/cientos'

const props = defineProps({
  position: {
    type: Array,
    default: () => [0, 0, 0]
  },
  color: {
    type: String,
    default: '#00cfff'
  },
  count: {
    type: Number,
    default: 60
  }
})
</script>

<template>
  <Sparkles
    :position="props.position"
    :count="props.count"
    :scale="3"
    :size="1.5"
    :speed="0.4"
    :color="props.color"
  />
</template>
