// src/components/scene/Scene.jsx
import { Canvas } from "@react-three/fiber";
import { OrbitControls, Stars } from "@react-three/drei";
import Lights from "./Lights";
import FloatingPanel from "../objects/FloatingPanel";
import NeonLine from "../objects/NeonLine";
import ParticleCloud from "../objects/ParticleCloud";
import ServerBox from "../objects/ServerBox";
import BloomEffect from "../effects/BloomEffect";

export default function Scene() {
  return (
    <Canvas
      camera={{ position: [0, 1, 8], fov: 60 }}
      style={{ background: "#080810" }}
    >
      <Lights />
      <Stars radius={60} depth={50} count={3000} factor={3} fade />

      {/* LEFT CLUSTER — tools & icons */}
      <FloatingPanel position={[-4.5, 0.5, 0]} color="#7b2fff" />
      <FloatingPanel
        position={[-3.8, -0.4, 0.5]}
        color="#00cfff"
        size={[1, 0.7, 0.02]}
      />
      <FloatingPanel
        position={[-5, -0.2, -0.3]}
        color="#7b2fff"
        size={[0.8, 0.6, 0.02]}
      />
      <ParticleCloud position={[-4, 0, 0]} color="#7b2fff" count={50} />

      {/* NEON LINES connecting left → center */}
      <NeonLine
        color="#00cfff"
        points={[
          [-3, 0, 0],
          [-1.5, 0, 0],
        ]}
      />
      <NeonLine
        color="#7b2fff"
        points={[
          [-3, -0.3, 0],
          [-1.5, -0.3, 0],
        ]}
      />

      {/* CENTER — main monitor/screen panels */}
      <FloatingPanel
        position={[0, 0.6, 0]}
        size={[2.2, 1.4, 0.02]}
        color="#00cfff"
        speed={1}
      />
      <FloatingPanel
        position={[0.3, 0.4, -0.3]}
        size={[2, 1.2, 0.02]}
        color="#7b2fff"
        speed={0.8}
      />
      <FloatingPanel
        position={[-0.2, 0.2, -0.6]}
        size={[1.8, 1, 0.02]}
        color="#00cfff"
        speed={1.2}
      />
      <ServerBox position={[1.5, -0.3, 0]} />

      {/* NEON LINES connecting center → right */}
      <NeonLine
        color="#00cfff"
        points={[
          [1.5, 0.3, 0],
          [3, 0.6, 0],
        ]}
      />
      <NeonLine
        color="#7b2fff"
        points={[
          [1.5, 0, 0],
          [3, -0.2, 0],
        ]}
      />
      <NeonLine
        color="#00cfff"
        points={[
          [1.5, -0.3, 0],
          [3, -0.8, 0],
        ]}
      />

      {/* RIGHT CLUSTER — neural net / database */}
      <FloatingPanel
        position={[4.5, 1, 0]}
        size={[0.7, 0.7, 0.02]}
        color="#00cfff"
      />
      <FloatingPanel
        position={[5, 0.2, 0]}
        size={[0.7, 0.7, 0.02]}
        color="#7b2fff"
      />
      <FloatingPanel
        position={[4.2, -0.5, 0]}
        size={[0.7, 0.7, 0.02]}
        color="#00cfff"
      />
      <FloatingPanel
        position={[5.2, -0.3, 0.3]}
        size={[0.6, 0.6, 0.02]}
        color="#7b2fff"
      />
      <ParticleCloud position={[4.8, 0.3, 0]} color="#00cfff" count={40} />

      {/* Postprocessing */}
      <BloomEffect />

      {/* Camera Controls */}
      <OrbitControls
        enableZoom={true}
        enablePan={false}
        minDistance={4}
        maxDistance={14}
        autoRotate
        autoRotateSpeed={0.4}
      />
    </Canvas>
  );
}

// src/components/scene/Scene.vue
<script setup>
import { TresCanvas } from '@tresjs/core'
import { OrbitControls, Stars } from '@tresjs/cientos'
import Lights from './Lights.vue'
import ExplodedStack from '../objects/ExplodedStack.vue'
import AppMonitor from '../objects/AppMonitor.vue'
import NeuralNet from '../objects/NeuralNet.vue'
import NeonLine from '../objects/NeonLine.vue'
import ParticleCloud from '../objects/ParticleCloud.vue'
import BloomEffect from '../effects/BloomEffect.vue'

const props = defineProps({
  autoRotate: {
    type: Boolean,
    default: true
  },
  starsActive: {
    type: Boolean,
    default: true
  },
  bloomIntensity: {
    type: Number,
    default: 2.5
  },
  neonColor: {
    type: String,
    default: '#00cfff'
  }
})

const emit = defineEmits(['select-panel'])

// Isometric neon routing pathways (orthogonal paths routing along grid layout)
const routeLeftToCenter1 = [
  [-3.4, -0.6, 1.0],
  [-1.9, -0.6, 1.0],
  [-1.9, 0.1, 0.1],
  [-1.2, 0.1, 0.1]
]

const routeLeftToCenter2 = [
  [-3.2, -0.9, 1.3],
  [-1.6, -0.9, 0.8],
  [-1.6, 0.3, 0.3],
  [-1.0, 0.3, 0.3]
]

const routeCenterToRight1 = [
  [1.9, 0.1, -0.2],
  [2.8, 0.1, -0.2],
  [2.8, 0.8, -1.0],
  [3.6, 0.8, -1.0]
]

const routeCenterToRight2 = [
  [1.7, -0.2, -0.4],
  [2.5, -0.2, -0.4],
  [2.5, 0.5, -1.2],
  [3.3, 0.5, -1.2]
]
</script>

<template>
  <TresCanvas
    clear-color="#080810"
  >
    <TresPerspectiveCamera :position="[8.0, 5.5, 10.0]" :fov="50" />
    <Lights />
    
    <!-- Cybernetic Stars Background (disabled by default, reduced count) -->
    <Stars
      v-if="props.starsActive"
      :radius="60"
      :depth="50"
      :count="800"
      :factor="1.5"
      fade
    />

    <!-- LEFT CLUSTER: Exploded chip stack & core developer tools -->
    <ExplodedStack
      :position="[-4.5, -0.6, 1.5]"
      :neon-color="props.neonColor"
      @select-panel="emit('select-panel', $event)"
    />
    <ParticleCloud :position="[-4.5, -0.6, 1.5]" :color="props.neonColor" :count="40" />

    <!-- CENTER CLUSTER: Layered workspace panels & server unit -->
    <AppMonitor
      :position="[0, 0.1, 0]"
      :neon-color="props.neonColor"
      @select-panel="emit('select-panel', $event)"
    />

    <!-- RIGHT CLUSTER: Neural Net and database layers -->
    <NeuralNet
      :position="[4.5, 0.8, -1.5]"
      :neon-color="props.neonColor"
      @select-panel="emit('select-panel', $event)"
    />
    <ParticleCloud :position="[4.5, 0.8, -1.5]" color="#7b2fff" :count="30" />

    <!-- ISOMETRIC NEON PIPELINES (Data flow paths) -->
    <!-- Left to Center (cyan/preset) -->
    <NeonLine
      :color="props.neonColor"
      :points="routeLeftToCenter1"
    />
    <!-- Left to Center (purple) -->
    <NeonLine
      color="#7b2fff"
      :points="routeLeftToCenter2"
    />
    <!-- Center to Right (cyan/preset) -->
    <NeonLine
      :color="props.neonColor"
      :points="routeCenterToRight1"
    />
    <!-- Center to Right (purple) -->
    <NeonLine
      color="#7b2fff"
      :points="routeCenterToRight2"
    />

    <!-- Glowing Bloom Postprocessing -->
    <BloomEffect :intensity="props.bloomIntensity" />

    <!-- Camera Navigation Controls -->
    <OrbitControls
      :enable-zoom="true"
      :enable-pan="false"
      :min-distance="4"
      :max-distance="16"
      :auto-rotate="props.autoRotate"
      :auto-rotate-speed="0.25"
    />
  </TresCanvas>
</template>
